### ISSUE TITLE
missing option to list configs

### ISSUE THREAD

**Issue by fenio** [radraw/kube-switch-config#1]
Looking at help output seems that switch-config should support -l option.
I suppose it should list available configs.

(⎈|co-mom-personal-ctx:stack)➜  ~ kubectl switch-config -h

Usage:
	 kubectl switch-config [-h] [-l] | [<name>]

I can implement it if that helps ;)

Thanks for useful kubectl plugin.

**Comment by radraw** [comment]
Indeed the feature is obviously missing :( I will try to prepare implementation in near feature. I'm glad to hear this plugin is useful and thank you for your will to contribute. For the moment it seems I should have some time to implement it and I would like to go through the path of updating a plugin for the first time :)

**Comment by radraw** [comment]
It has been implemented so closing the issue.

**Comment by fenio** [comment]
Are you planning to update krew index too?
